### PR TITLE
Feature 1 changes into master

### PR DESCRIPTION
**Pull request by githubSRK1**
Hi, i developed feature-1, it is good to merge with master.

### CODE REVIEW

**Comment by Srikonda-github** [comment]
Hi, I developed feature-1, it is good to merge with master.

**Review by githubSRK1 — COMMENTED** [review]
Why is this line added? Is it really required.?

**Review by githubSRK1 — COMMENTED** [review]
Everything seems good, approving this.

**Comment by githubSRK1** [comment]
Why is this line added? is it really necessary.

**Pull request merged**
